apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ordino.fullname" . }}-configuration
  labels:
    {{- include "ordino.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "phovea_server": {
        "debug": false,
        "port": 9000,
      },
      "tdp_core": {
        "host": "{{ .Values.ordino.mongodb.host }}",
        "port": {{ .Values.ordino.mongodb.port }},
        "database": "targid"
      },
      "phovea_data_mongo": {
        "host": "@{{ .Values.ordino.mongodb.host }}",
        "port": {{ .Values.ordino.mongodb.port }},
        "db": "graph"
      },
      "phovea_data_redis": {
        "assigner": {
          "hostname": "{{ .Values.ordino.redis.host }}"
        },
        "mapping": {
          "hostname": "{{ .Values.ordino.redis.host }}"
        }
      },
      "tdp_publicdb": {
        "dburl": "postgresql://USER:PASS@HOST/DBNAME",
        "statement_timeout": "'5min'"
      }
    }