apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ordino.fullname" . }}-configuration
  labels:
    {{- include "ordino.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "phovea_server": {
        "debug": false,
        "port": 9000,
      },
      "tdp_core": {
        "host": "localhost"
      },
      "phovea_data_mongo": {
        "host": "localhost"
      },
      "phovea_data_redis": {
        "assigner": {
          "hostname": "localhost"
        },
        "mapping": {
          "hostname": "localhost"
        }
      },
      "tdp_publicdb": {
        "dburl": "postgresql://USER:PASS@HOST/DBNAME",
        "statement_timeout": "'5min'"
      }
    }
