apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ordino.fullname" . }}-web
  labels:
    {{- include "ordino.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ordino.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ordino.selectorLabels" . | nindent 8 }}
        ordino-part: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ordino.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: {{ .Values.ordino.web.image }}:{{ .Values.ordino.web.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PHOVEA_API_SERVER
              value: {{ include "ordino.fullname" . }}-server
          ports:
            - name: http
              containerPort: {{ .Values.ordino.web.port }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "ordino.fullname" . }}-configuration-volume
          configMap:
            name: {{ include "ordino.fullname" . }}-configuration
