apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ordino.fullname" . }}
  labels:
    {{- include "ordino.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ordino.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ordino.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ordino.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: caleydo/ordino:starter
          env:
            - name: PHOVEA_API_SERVER
              value: localhost:9000
          ports:
            - name: web
              containerPort: 80
        - name: server
          image: caleydo/ordino_server:starter
          ports:
            - name: server
              containerPort: 9000
          volumeMounts:
            - name: {{ include "ordino.fullname" . }}-configuration-volume
              mountPath: /phovea.config
          env:
            - name: PHOVEA_CONFIG_PATH
              value: /phovea.config/config.json
        - name: db-mongo
          image: mongo:3.2
        - name: db-redis
          image: redis:3.2-alpine

        {{- /*
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        */ -}}


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "ordino.fullname" . }}-configuration-volume
          configMap:
            name: {{ include "ordino.fullname" . }}-configuration
